# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1074e95f5d4a0a2c118690db8e3f8855ea1acf8c331a085a4802ff20db9555221730bc9e9078a477009987730465c66cb8648cb546b96deea458cc48c6c449ed

test:
  secret_key_base: c36bf6a7876a85f1bb6e6cb03890e69deaf3a3d30f54b221520dd40d182d2a11d253b8b0d1ec149c64e6d7341c0af54748415b992ba87a7763add17508fa0b0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
